name: Build PyInstaller Binary

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller colorama

    - name: Build binary
      run: |
        pyinstaller --onefile --name gamepach gamepach.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gamepach-binary
        path: dist/gamepach
