name: Build PyInstaller ARM Binary

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build-arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ "aarch64" ]   # চাইলে "armv7" ও যোগ করতে পারো
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Build inside ARM docker
      run: |
        if [ "${{ matrix.arch }}" = "aarch64" ]; then
          DOCKER_IMG=arm64v8/python:3.11-slim
          OUTPUT_NAME=gamepach_arm64
        else
          DOCKER_IMG=arm32v7/python:3.11-slim
          OUTPUT_NAME=gamepach_armv7
        fi

        docker run --rm -v "$PWD":/src -w /src --env OUTPUT_NAME="$OUTPUT_NAME" $DOCKER_IMG /bin/bash -lc "
          apt-get update -qq && apt-get install -y build-essential zip ca-certificates >/dev/null 2>&1 || true
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pyinstaller colorama
          pyinstaller --onefile --name \$OUTPUT_NAME gamepach.py
          mkdir -p /src/dist_artifacts
          cp dist/\$OUTPUT_NAME /src/dist_artifacts/ || true
        "

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gamepach-arm
        path: dist_artifacts/*
